-- Phase 2: Column-level metadata for agent-ready data export
-- Stores semantic metadata generated by LLM enrichment

-- Column-level metadata (persists LLM-generated column semantics)
CREATE TABLE IF NOT EXISTS datawarp.tbl_column_metadata (
    canonical_source_code VARCHAR(100) NOT NULL,
    column_name VARCHAR(100) NOT NULL,

    -- From LLM enrichment (already generated by enrich_manifest.py)
    original_name VARCHAR(500),            -- Original Excel/CSV header (NHS headers can be very long)
    description TEXT,                      -- What this column measures
    data_type VARCHAR(50),                 -- integer, varchar, numeric, date
    is_dimension BOOLEAN DEFAULT FALSE,    -- Is this a grouping column?
    is_measure BOOLEAN DEFAULT FALSE,      -- Is this a numeric metric?
    query_keywords TEXT[],                 -- Search terms for semantic discovery

    -- From data profiling (populated post-load by profile_metadata.py)
    min_value NUMERIC,                     -- Observed minimum value
    max_value NUMERIC,                     -- Observed maximum value
    null_rate NUMERIC(5,2),                -- Percentage of null values
    distinct_count INTEGER,                -- Number of distinct values

    -- Metadata provenance
    metadata_source VARCHAR(20) DEFAULT 'llm',  -- llm | profiled | manual
    confidence NUMERIC(3,2) DEFAULT 0.70,       -- 0.0-1.0 confidence score
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    PRIMARY KEY (canonical_source_code, column_name),
    FOREIGN KEY (canonical_source_code) REFERENCES datawarp.tbl_canonical_sources(canonical_code)
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_column_metadata_source
    ON datawarp.tbl_column_metadata(canonical_source_code);

CREATE INDEX IF NOT EXISTS idx_column_metadata_keywords
    ON datawarp.tbl_column_metadata USING gin(query_keywords);

CREATE INDEX IF NOT EXISTS idx_column_metadata_confidence
    ON datawarp.tbl_column_metadata(confidence);

-- Comments for documentation
COMMENT ON TABLE datawarp.tbl_column_metadata IS
    'Column-level semantic metadata for Parquet export and agent querying';

COMMENT ON COLUMN datawarp.tbl_column_metadata.query_keywords IS
    'Array of searchable terms for semantic discovery (e.g., ["smoker count", "total smokers"])';

COMMENT ON COLUMN datawarp.tbl_column_metadata.confidence IS
    '0.70 = LLM inference, 0.95 = profiled validation, 1.00 = manual verification';

-- Extend existing canonical sources table with dataset-level metadata
ALTER TABLE datawarp.tbl_canonical_sources
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS metadata JSONB,  -- record_type, granularity, measures, etc.
    ADD COLUMN IF NOT EXISTS domain VARCHAR(50);  -- clinical, financial, operational

-- Index for domain filtering
CREATE INDEX IF NOT EXISTS idx_canonical_domain
    ON datawarp.tbl_canonical_sources(domain);

-- Comments for new columns
COMMENT ON COLUMN datawarp.tbl_canonical_sources.description IS
    'Human-readable description of what this dataset contains';

COMMENT ON COLUMN datawarp.tbl_canonical_sources.metadata IS
    'JSONB structure: {record_type, granularity, measures, dimensions, tags, related_to}';

COMMENT ON COLUMN datawarp.tbl_canonical_sources.domain IS
    'Data domain: clinical, financial, operational, reference';
