#!/usr/bin/env python3
"""
Process all failed sources from nhs_landing_pages.md using deep explorer.
Appends results to publications2.yaml.
"""

import re
import sys
import time

# Failed sources from nhs_landing_pages.md (❌ status)
FAILED_SOURCES = [
    ("autism", "Autism Waiting Time Statistics", "https://digital.nhs.uk/data-and-information/publications/statistical/autism-waiting-time-statistics"),
    ("bed_occupancy", "Bed Availability and Occupancy", "https://www.england.nhs.uk/statistics/statistical-work-areas/bed-availability-and-occupancy/"),
    ("cancelled_ops", "Cancelled Elective Operations", "https://www.england.nhs.uk/statistics/statistical-work-areas/cancelled-elective-operations/"),
    ("diagnostics", "Diagnostic Waiting Times", "https://www.england.nhs.uk/statistics/statistical-work-areas/diagnostics-waiting-times-and-activity/"),
    ("fft", "Friends and Family Test", "https://www.england.nhs.uk/statistics/statistical-work-areas/friends-and-family-test/"),
    ("mrr", "Monthly Outpatient Referrals", "https://www.england.nhs.uk/statistics/statistical-work-areas/outpatient-referrals/"),
    ("msa", "Mixed Sex Accommodation", "https://www.england.nhs.uk/statistics/statistical-work-areas/mixed-sex-accommodation/"),
    ("proms", "Patient Reported Outcome Measures", "https://www.england.nhs.uk/statistics/statistical-work-areas/proms/"),
    ("satod", "Smoking Status at Time of Delivery", "https://digital.nhs.uk/data-and-information/publications/statistical/statistics-on-women-s-smoking-status-at-time-of-delivery-england"),
    ("talking_therapies", "Psychological Therapies", "https://digital.nhs.uk/data-and-information/publications/statistical/psychological-therapies-annual-reports"),
]

# Skip these (external sites, special access, etc.)
SKIP_SOURCES = [
    "Infection Control",  # gov.uk
    "LAS Handovers",  # external
    "NHS Staff Survey",  # external
    "PIFU",  # policy page
    "Patient Safety (NRLS)",  # discontinued
    "Personal Health Budgets",  # publication page
]

def main():
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from deep_explore_source import deep_explore, generate_yaml, fetch_page

    print(f"🔍 Processing {len(FAILED_SOURCES)} failed sources...\n")

    all_yaml = []
    success = 0
    failed = []

    for code, name, url in FAILED_SOURCES:
        print(f"\n{'='*60}")
        print(f"📊 {name}")
        print(f"   {url}")

        try:
            results = deep_explore(url, max_depth=4)

            if results:
                yaml, count = generate_yaml(code, name, url, results)
                all_yaml.append(yaml)
                success += 1
                print(f"\n   ✅ Found {count} periods")
            else:
                failed.append((code, name, url))
                print(f"\n   ❌ No data files found")
        except Exception as e:
            failed.append((code, name, url))
            print(f"\n   ❌ Error: {e}")

        time.sleep(2)  # Rate limiting

    # Output combined YAML
    print(f"\n\n{'='*60}")
    print(f"📋 SUMMARY")
    print(f"   ✅ Success: {success}/{len(FAILED_SOURCES)}")
    print(f"   ❌ Failed: {len(failed)}")

    if failed:
        print(f"\n   Still need manual review:")
        for code, name, url in failed:
            print(f"      - {name}")

    if all_yaml:
        print(f"\n{'='*60}")
        print("YAML TO APPEND TO publications2.yaml:")
        print("="*60)
        for yaml in all_yaml:
            print(yaml)

        # Optionally append to file
        if len(sys.argv) > 1 and sys.argv[1] == '--append':
            with open('config/publications2.yaml', 'a') as f:
                f.write("\n\n  # === AUTO-GENERATED BY deep_explore === \n")
                for yaml in all_yaml:
                    f.write(yaml)
            print(f"\n✅ Appended to config/publications2.yaml")

if __name__ == "__main__":
    main()
